export {
    assertNever,
    deepClone,
    deepEqual,
    deepMerge,
    generateRandom,
    generateUUID,
    getHashParam,
    getUrlParam,
    isArray,
    isBoolean,
    isDefined,
    isEmpty,
    isFunction,
    isNumber,
    isObject,
    isString,
    isValidURL,
    setHashParam,
    setUrlParam,
    shallowClone,
    shallowEqual,
    shallowMerge
} from './universalCommon';
